export class Design {
  constructor(
    public id: string = null,
    public kva: number = null,
    public marca: string = null,
    public fecha: Date = null,
    public fase: number = null,
    public voltajeNominalPrimario: number = null,
    public voltajeNominalSecundario: number = null,
    public tipoDeNucleo: string = null,
    public formaDelNucleo: string = null,
    public cantidadDeFe: number = null,
    public anchoDeFe: number = null,
    public anchoVentana: number = null,
    public altoVentana: number = null,
    public conductorSecundario: string = null,
    public grupoConnection: string = null,
    public tipoLaminaMagnetic: string = null,
    public positionNominalConmutador: number = null,
    public pesoNucleo1: number = null,
    public pesoNucleo2: number = null,
    public pesoTotal: number = null,
    public poW: number = null,
    public induction: string = null,
    public inductionTDesign: number = null,
    public connectionBajaTension: string = null,
    public connectionAltaTension: string = null,
    public lmn1: number = null,
    public lmn2: number = null,
    public anet: number = null,
    public wkgCalculado: number = null,
    public wkgTablaLamina: number = null,
    public inductionTablaLamina: number = null,
    public inductionIngresoManual: number = null,
    public cantidadAceite: number = null,
    public tipoAceite: string = null,
    public tipoTransformador: string = null
  ) {}
}
